# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Schedule-cronjob-deploy

on:
  schedule:
    - cron: "17 13 * * *"
  workflow_dispatch:
env:
  MAIL_USER_EMAIL: ${{ secrets.MAIL_USER_EMAIL}}
  MAIL_USER_PASSWORD: ${{ secrets.MAIL_USER_PASSWORD}}
  MAIL_TO: ${{ secrets.MAIL_TO}}
  ACCUWEATHER_API_KEY: ${{ secrets.ACCUWEATHER_API_KEY}}

jobs:
  report:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: node src/main.js
